// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWeSUB02pCFCXXaSH47xFSBY1m8QuuZ2w',
    appId: '1:958094605442:web:35712d36fc7114c812489b',
    messagingSenderId: '958094605442',
    projectId: 'safetraverse',
    authDomain: 'safetraverse.firebaseapp.com',
    databaseURL: 'https://safetraverse-default-rtdb.firebaseio.com',
    storageBucket: 'safetraverse.appspot.com',
    measurementId: 'G-76T40W496B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbC8arUXhQqP1873QgYy2lHKpXSuhtx_c',
    appId: '1:958094605442:android:062178a0aa89063812489b',
    messagingSenderId: '958094605442',
    projectId: 'safetraverse',
    databaseURL: 'https://safetraverse-default-rtdb.firebaseio.com',
    storageBucket: 'safetraverse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlx03yfGyoE5lann3Wnx-PnhC4iEVdMSo',
    appId: '1:958094605442:ios:7ed98307444bee8d12489b',
    messagingSenderId: '958094605442',
    projectId: 'safetraverse',
    databaseURL: 'https://safetraverse-default-rtdb.firebaseio.com',
    storageBucket: 'safetraverse.appspot.com',
    iosBundleId: 'com.example.safer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlx03yfGyoE5lann3Wnx-PnhC4iEVdMSo',
    appId: '1:958094605442:ios:7ed98307444bee8d12489b',
    messagingSenderId: '958094605442',
    projectId: 'safetraverse',
    databaseURL: 'https://safetraverse-default-rtdb.firebaseio.com',
    storageBucket: 'safetraverse.appspot.com',
    iosBundleId: 'com.example.safer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWeSUB02pCFCXXaSH47xFSBY1m8QuuZ2w',
    appId: '1:958094605442:web:44932b0521f29cd412489b',
    messagingSenderId: '958094605442',
    projectId: 'safetraverse',
    authDomain: 'safetraverse.firebaseapp.com',
    databaseURL: 'https://safetraverse-default-rtdb.firebaseio.com',
    storageBucket: 'safetraverse.appspot.com',
    measurementId: 'G-RCEK9RGRNF',
  );
}
